#!/bin/bash
# supported_cluster_sizes=(24 30 36 42 48 54 60 66 72 78 84 90)
#supported_cluster_sizes=(24 30 36)
#supported_cluster_sizes=(42 48 54)
#supported_cluster_sizes=(48 54 60 66)
#supported_cluster_sizes=(72 78)
#supported_cluster_sizes=(84 90)
supported_cluster_sizes=(6 12 18)

for cluster_size in "${supported_cluster_sizes[@]}"; do
    echo "ClusterSize $cluster_size"

#    sed -i "0,/=48/s//=12/" ClusterSize_BarAndChar$cluster_size/BAR1/job.scr
    cd ClusterSize_BarAndChar$cluster_size/
    echo "Bar Sim output for Cluster Size $cluster_size " > BarSimOutPutClusterSize$cluster_size
    cd BAR1
    gfortran bar.f90
    echo "Bar1" >> ../BarSimOutPutClusterSize$cluster_size
    ./a.out >> ../BarSimOutPutClusterSize$cluster_size
    cd ../
    cd BAR2
    gfortran bar.f90
    echo "Bar2" >> ../BarSimOutPutClusterSize$cluster_size
    ./a.out >> ../BarSimOutPutClusterSize$cluster_size
    cd ../
    cd BAR3
    gfortran bar.f90
    echo "Bar3" >> ../BarSimOutPutClusterSize$cluster_size
    ./a.out >> ../BarSimOutPutClusterSize$cluster_size
    cd ../
    cd BAR4
    gfortran bar.f90
    echo "Bar4" >> ../BarSimOutPutClusterSize$cluster_size
    ./a.out >> ../BarSimOutPutClusterSize$cluster_size
    cd ../
    cd ../



#   sed -i "0,/0,0.26/s//0.26,0.52/" ClusterSize_BarAndChar$cluster_size/BAR2/in.lmp
#   sed -i "0,/0,0.26/s//0.52,0.78/" ClusterSize_BarAndChar$cluster_size/BAR3/in.lmp
#   sed -i "0,/0,0.26/s//0.78,1.02/" ClusterSize_BarAndChar$cluster_size/BAR4/in.lmp
#   sed -i "0,/39000000/s//36000000/" ClusterSize_BarAndChar$cluster_size/BAR4/in.lmp
#
#   cd ClusterSize_BarAndChar$cluster_size/BAR1/
#   jobID=$(qsub job.scr | awk '{print substr($1, 1, 5)}')
#   echo "Submitted job $jobID"
#   cd ../..
#
#   cd ClusterSize_BarAndChar$cluster_size/BAR2/
#   jobID=$(qsub job.scr | awk '{print substr($1, 1, 5)}')
#   echo "Submitted job $jobID"
#   cd ../..
#
#   cd ClusterSize_BarAndChar$cluster_size/BAR3/
#   jobID=$(qsub job.scr | awk '{print substr($1, 1, 5)}')
#   echo "Submitted job $jobID"
#   cd ../..
#
#   cd ClusterSize_BarAndChar$cluster_size/BAR4/
#   jobID=$(qsub job.scr | awk '{print substr($1, 1, 5)}')
#   echo "Submitted job $jobID"
#   cd ../..

    # Check if the job is still running
#   x=$(qstat $jobID 2>&1 | awk '{print substr($0, 1, 5)}')
#
#   while [ "$x" != "qstat" ]; do
#       echo "Job $jobID is still running"
#       sleep 5
#       x=$(qstat $jobID 2>&1 | awk '{print substr($0, 1, 5)}')
#   done
#
#   # The job has finished running
#   echo "Job $jobID has completed."
#
#   # Run qsub job.scr2
#   #qsub job.scr2
#   jobID2=$(qsub job.scr2 | awk '{print substr($1, 1, 5)}')
#
#   # Check if the job is still running
#   x=$(qstat $jobID2 2>&1 | awk '{print substr($0, 1, 5)}')
#
#   while [ "$x" != "qstat" ]; do
#       echo "Job $jobID2 is still running"
#       sleep 5
#       x=$(qstat $jobID2 2>&1 | awk '{print substr($0, 1, 5)}')
#   done
#
#   # The job has finished running
#   echo "Job $jobID2 has completed."
#
#   gfortran delta_Fcoul.f90    
#
#   echo "charges Sim output for Cluster Size $cluster_size " > ChargesSimOutPutClusterSize$cluster_size
#   ./a.out >> ChargesSimOutPutClusterSize$cluster_size
#
#   cd ../../
done

cat $(ls -v ClusterSize_BarAndChar*/BarSim*)
